"""add role and content to ChatHistory

Revision ID: 282c4e2f0057
Revises: 
Create Date: 2025-05-09 22:55:34.552122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282c4e2f0057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('budgets',
    # All table creation/commented out to avoid errors on existing DB
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('moods')
    op.drop_table('chat_history')
    op.drop_table('budgets')
    # ### end Alembic commands ###
