"""fix_mood_session_relationship

Revision ID: 2abc4547bc54
Revises: 3e7461bada6f
Create Date: 2025-06-07 00:13:30.119217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abc4547bc54'
down_revision: Union[str, None] = '3e7461bada6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mood_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mood_sessions', type_='foreignkey')
    # ### end Alembic commands ###
