"""add summary field to mood_sessions

Revision ID: 2fb45381382d
Revises: cf606998e6cb
Create Date: 2025-06-25 19:13:48.863537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb45381382d'
down_revision: Union[str, None] = 'cf606998e6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_sessions', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_sessions', 'summary')
    # ### end Alembic commands ###
