"""update_model_relationships

Revision ID: 3e7461bada6f
Revises: afbee0b74039
Create Date: 2025-05-28 21:33:15.253032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7461bada6f'
down_revision: Union[str, None] = 'afbee0b74039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('budgets_user_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('goals_user_id_fkey', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_user_id_fkey', 'goals', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_user_id_fkey', 'budgets', 'users', ['user_id'], ['id'])
    op.drop_table('transactions')
    # ### end Alembic commands ###
