"""add perma_scores field to mood_sessions

Revision ID: 53585b464317
Revises: e08c2b1e241c
Create Date: 2025-06-25 19:06:48.459365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53585b464317'
down_revision: Union[str, None] = 'e08c2b1e241c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_sessions', sa.Column('perma_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_sessions', 'perma_scores')
    # ### end Alembic commands ###
