"""add_mobile_number_field_to_user

Revision ID: 60086fa223ae
Revises: 2fb45381382d
Create Date: 2025-06-26 09:43:55.834789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60086fa223ae'
down_revision: Union[str, None] = '2fb45381382d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###
