"""Add advanced goal fields

Revision ID: c63c3b0f7710
Revises: 60086fa223ae
Create Date: 2025-06-26 17:46:04.357486

"""
from sqlalchemy import Text
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63c3b0f7710'
down_revision: Union[str, None] = '60086fa223ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('milestones', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('reminders', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('vision', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('mood_aware', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'mood_aware')
    op.drop_column('goals', 'vision')
    op.drop_column('goals', 'reminders')
    op.drop_column('goals', 'milestones')
    op.drop_column('goals', 'milestone_frequency')
    # ### end Alembic commands ###
