"""add answers field to mood_sessions

Revision ID: cf606998e6cb
Revises: 53585b464317
Create Date: 2025-06-25 19:10:41.855230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf606998e6cb'
down_revision: Union[str, None] = '53585b464317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_sessions', sa.Column('answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_sessions', 'answers')
    # ### end Alembic commands ###
