"""add role and content to ChatHistory

Revision ID: eca952bb4807
Revises: 282c4e2f0057
Create Date: 2025-05-09 22:59:07.373173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca952bb4807'
down_revision: Union[str, None] = '282c4e2f0057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add 'role' and 'content' columns to chat_history table
    op.add_column('chat_history', sa.Column('role', sa.String(), nullable=True))
    op.add_column('chat_history', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
